title: Tibor
author: Tibor
url: "https://thefallofjohannm.github.io"
language: "cs-cz"

logo: /assets/img/logo.jpeg
description: Spisy + hudba
show_downloads: false
color-scheme: dark
date-format: "%d %B %Y"
permalink: /:categories/:title

sidebar:
  - name: Home
    icon: <i class="fa-solid fa-home"></i>
    link: /
  - name: About
    icon: <i class="fa-solid fa-circle-info"></i>
    link: /about/
  - name: References
    icon: <i class="fa-solid fa-newspaper"></i>
    link: /references/
  - name: Music
    icon: <i class="fa-solid fa-pencil"></i>
    link: /music/
  - name: Poetry
    icon: <i class="fa-solid fa-paper-plane"></i>
    link: /poetry/
  - name: Repository
    icon: <i class="fa-sharp fa-solid fa-code"></i>
    link: https://github.com/MatejHosek/MatejHosek.github.io/
  - name: Atom feed
    icon: <i class="fa-solid fa-rss"></i>
    link: /feed.xml


collections:
  posts:
    output: true
  poems:
    output: true


plugins:
  - jektex


jektex:
  cache_dir: ".jekyll-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

